### ISSUE TITLE
Error installing Easee integration "Unable to install package pyeasee==0.7.55: ERROR: Will not install to the user site because it will lack sys.path precedence to msgpack"

### ISSUE THREAD

**Issue by bottels** [nordicopen/easee_hass#391]
### Question

Hi guys,

When trying to install the package using HACS (or manually), I get the following message:

`Unable to install package pyeasee==0.7.55: ERROR: Will not install to the user site because it will lack sys.path precedence to msgpack in /snap/home-assistant-snap/592/lib/python3.12/site-packages`

I tried adding PYTHONPATH to /etc/environment, but no luck. I have a snap installation on an Ubuntu server.

### What version of the integration are you using?

easee-0.9.57

### Anything in the logs that might be useful for us?

```txt
Traceback (most recent call last):
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/components/config/config_entries.py", line 147, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/config_entries.py", line 888, in async_init
    flow, result = await task
                   ^^^^^^^^^^
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/config_entries.py", line 906, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/config_entries.py", line 1009, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/config_entries.py", line 2106, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/config_entries.py", line 2082, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/setup.py", line 466, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/requirements.py", line 52, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/requirements.py", line 168, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/requirements.py", line 183, in _async_process_integration
    await self.async_process_requirements(
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/requirements.py", line 248, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/snap/home-assistant-snap/592/lib/python3.12/site-packages/homeassistant/requirements.py", line 286, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for easee not found: ['pyeasee==0.7.55'].
```

**Comment by olalid** [comment]
This might be the same issue as this one: https://github.com/nordicopen/easee_hass/issues/292
Unfortunately I do not know what the resolution was, but I do not think this is a problem with this component.

**Comment by bottels** [comment]
Indeed the same issue, apologies. I'll close this one, and check if a solution has been found. Thanks.
