### ISSUE TITLE
Error after upgrading to version 0.9.62 (From 09.61)

### ISSUE THREAD

**Issue by MZBjerg** [nordicopen/easee_hass#489]
### Before creating an issue...

- [X] There is no open issue describing the same problem
- [X] I am running latest versions of the integration and of Home Assistant
- [X] I have checked the operational status of the Easee API

### The problem

I upgraded the new version. After restart I got error in the log. 

Removed the installation completely, and downloaded the new version again. 

When I try to add integration i get error: 

Error
Config flow could not be loaded: {"message":"Invalid handler specified"} 

Any advice how to fix the error?

br. 
Morten

### Version of Easee integration having the issue?

0.9.62

### Version of Home Assistant Core having the issue?

2024.10.2

### Anything in the logs that might be useful for us?

```txt
From my log i find this:
Logger: homeassistant.util.package
Source: util/package.py:78
First occurred: 17:06:17 (1 occurrences)
Last logged: 17:06:17

Installed version for pyeasee resolved to None


and:
Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 17:06:23 (1 occurrences)
Last logged: 17:06:23

Detected blocking call to import_module with args ('custom_components.easee.config_flow',) inside the event loop by integration 'config' at homeassistant/components/config/config_entries.py, line 179: return await super()._post_impl(request, data) (offender: /usr/src/homeassistant/homeassistant/loader.py, line 1296: return importlib.import_module(f"{self.pkg_path}.{platform_name}")), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+config%22 For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle return await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper return await method(view, request, data, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post return await self._post_impl(request, data) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl return await super()._post_impl(request, data)

and;
Logger: homeassistant.config_entries
Source: config_entries.py:2945
First occurred: 17:06:23 (1 occurrences)
Last logged: 17:06:23

Error occurred loading flow for integration easee: cannot import name 'ChargerStreamData' from 'pyeasee' (/usr/local/lib/python3.12/site-packages/pyeasee/__init__.py)
```

**Comment by olalid** [comment]
I think the issue is that you have the wrong version of pyeasee.
It should update automatically, but possibly has not done so for you for some reason.
Do you have access to your python environment?
If so, do an ls /usr/local/lib/python3.12/site-packages/pyeasee* and you should see amongst other things something like this:
havenv/lib/python3.12/site-packages/pyeasee-0.8.5.dist-info:
I.e. you should have version 0.8.5.

See also https://github.com/nordicopen/easee_hass/issues/475 for another similar issue.

**Comment by MZBjerg** [comment]
I noticed almost all of my python was missing for some reason.

I restored a backup, and installed the integrations again, and now everything works fine again.

Strange how this happened.

Incident can be closed.

Thank you.

**Comment by ppuschmann** [comment]
Similar entry here:

```

No issues found for search term 'easee'
2024-11-13 18:56:37.236 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration easee which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-11-13 18:56:40.619 ERROR (ImportExecutor_0) [homeassistant.loader] Unexpected exception importing component custom_components.easee
  File "/config/custom_components/easee/__init__.py", line 11, in <module>
  File "/config/custom_components/easee/const.py", line 151, in <module>
2024-11-13 18:56:40.628 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.easee',) in /usr/src/homeassistant/homeassistant/loader.py, line 1071: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
2024-11-13 18:56:40.630 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.easee
  File "/config/custom_components/easee/__init__.py", line 11, in <module>
  File "/config/custom_components/easee/const.py", line 151, in <module>
ImportError: Exception importing custom_components.easee
  File "/config/custom_components/easee/__init__.py", line 11, in <module>
  File "/config/custom_components/easee/const.py", line 151, in <module>
2024-11-13 18:56:40.641 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'easee': Unable to import component: Exception importing custom_components.easee
  File "/config/custom_components/easee/__init__.py", line 11, in <module>
  File "/config/custom_components/easee/const.py", line 151, in <module>
ImportError: Exception importing custom_components.easee
  File "/config/custom_components/easee/__init__.py", line 11, in <module>
  File "/config/custom_components/easee/const.py", line 151, in <module>
ImportError: Exception importing custom_components.easee
```

**Comment by olalid** [comment]
Please do not continue to run v0.9.61. It has bugs that causes issues on the server side. See readme and/or release notes for  more info.

The actual error you see clearly indicates that the wrong version of pyeasee is installed, some version older than v0.8.5.
This is clear because that the error in line 151 in const.py indicates that it tries to use a constant with a new name that was introduced in pyeasee v0.8.5. So what is loaded is an older version of pyeasee where this constant has a different name.
The version of pyeasee must match what is stated in the components manifest.json file, and HA would normally install that version before it tries to load the component. v0.9.64 requires pyeasee v0.8.8. v0.9.61 requires v0.8.4. So you are likely trying to run v0.9.64 with pyeasee v0.8.4.
