### ISSUE TITLE
Issue with the new update 0.9.64

### ISSUE THREAD

**Issue by Lyngaae** [nordicopen/easee_hass#500]
### Before creating an issue...

- [X] There is no open issue describing the same problem
- [X] I am running latest versions of the integration and of Home Assistant
- [X] I have checked the operational status of the Easee API

### The problem

After updating to the latest version of the integration all my entities became unavailable.

### Version of Easee integration having the issue?

0.9.64

### Version of Home Assistant Core having the issue?

2024.10.4

**Comment by olalid** [comment]
Please look in the log file, we can not help you without more information.

**Comment by Lyngaae** [comment]
I was looking for the log files, but I am not sure where to find them.

2024-10-31 21:42:13.292 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration easee which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-10-31 21:42:28.057 ERROR (MainThread) [custom_components.easee.controller] Unexpected error creating device: 'Timeout' object does not support the context manager protocol
File "/config/custom_components/easee/controller.py", line 481, in initialize
File "/config/custom_components/easee/services.py", line 654, in circuit_execute_set_current
File "/config/custom_components/easee/services.py", line 384, in async_get_circuit_id
File "/config/custom_components/easee/diagnostics.py", line 37, in async_get_config_entry_diagnostics
2024-10-31 22:40:25.386 DEBUG (MainThread) [custom_components.easee.controller] Controller refcount after cleanup 5
2024-10-31 22:40:25.390 DEBUG (MainThread) [custom_components.easee] Setting up Easee component version 0.9.64
2024-10-31 22:40:25.390 INFO (MainThread) [pyeasee.easee] Easee python library version: 0.8.8

**Comment by astrandb** [comment]
> 'Timeout' object does not support the context manager protocol

This error has started to pop up in other integrations too - both core and custom_components. It should be addressed in HA 2024.11.0.b2 which is due today or tomorrow. Let us wait a while and see what the solution is.

**Comment by Lyngaae** [comment]
> I found this. [home-assistant/core#129592](https://github.com/home-assistant/core/pull/129592)

Hi astrandb
Thank you for taking your time to reply, and sorry i am not well enough in this subject, so i am not sure i understand, what you have found :)

Should i wait for a HA update?

**Comment by astrandb** [comment]
Yes, this problem is caused by a breaking change in an upstream library. It will be fixed in the next beta release of HA (tonight?) or in the official release on coming Wednesday.

**Comment by Lyngaae** [comment]
Thx for the explaination astrandb :)

**Comment by enoch85** [comment]
I don't know if this is releated, but just upgrade to latest HAOS and:

```
This error originated from a custom integration.

Logger: custom_components.easee.controller
Source: custom_components/easee/controller.py:481
integration: Easee EV Charger (documentation, issues)
First occurred: 19:51:08 (2 occurrences)
Last logged: 20:00:12

Unexpected error creating device: 'Timeout' object does not support the context manager protocol
Traceback (most recent call last):
  File "/config/custom_components/easee/controller.py", line 481, in initialize
    with timeout(TIMEOUT):
TypeError: 'Timeout' object does not support the context manager protocol
```

```
2024-11-06 20:00:12.067 ERROR (MainThread) [custom_components.easee.controller] Unexpected error creating device: 'Timeout' object does not support the context manager protocol
Traceback (most recent call last):
  File "/config/custom_components/easee/controller.py", line 481, in initialize
    with timeout(TIMEOUT):
TypeError: 'Timeout' object does not support the context manager protocol
2024-11-06 20:01:13.317 ERROR (SyncWorker_53) [custom_components.greenely.api] Failed to fetch produced electricity data, {"title":"404 Not Found","jwt":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3Mzg2OTUwNzAuMCwiYXV0aCI6eyJ1c2VyX2lkIjo0MTc3Mjd9fQ.o-vTcud5sm5NYmEPmZ3B5r7qhDaOHc1sTWw5bayvcQbIlPii1NSRlOsrdWwg5_619jPsYPExkyyGSHIVTtUBzQ"}
2024-11-06 20:05:44.354 ERROR (MainThread) [homeassistant.components.automation.test_tesla_stop] EV Smart - Garage STOPPA laddning: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 525, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 763, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 726, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/easee/services.py", line 737, in charger_execute_set_current
    charger_id = charger.id
                 ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
2024-11-06 20:05:44.359 ERROR (MainThread) [homeassistant.components.automation.test_tesla_stop] While executing automation automation.test_tesla_stop
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 742, in async_trigger
    return await self.action_script.async_run(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1795, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 463, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 527, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 557, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 525, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 763, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 726, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/easee/services.py", line 737, in charger_execute_set_current
    charger_id = charger.id
                 ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
```


None of the enteties are loading on my master Easeee Home.

**Comment by astrandb** [comment]
@enoch85 It is most likely same root cause. I suggest that you update your Home Assistant to 2024.11.0. It is being built in this moment an will be ready for download within an hour or so.

**Comment by enoch85** [comment]
Seems released: https://github.com/home-assistant/core/releases/tag/2024.11.0

**Comment by enoch85** [comment]
Pic or it didn't happen

![image](https://github.com/user-attachments/assets/ba29fd07-7663-4935-bd6e-60af3b10c52f)

**Comment by Lyngaae** [comment]
Haven’t received the update yet :(

**Comment by enoch85** [comment]
@Lyngaae Force the update check and you'll receive it :+1:

**Comment by Lyngaae** [comment]
I still have the issue.

**Comment by astrandb** [comment]
@Lyngaae Please check the logs (Settings->System->Logs) for lines from easee or pyeasee. 
Depending on if the integration loads or not you can also capture a diagnostic log for the Easee integration. 
Goto Settings->Devices & services -> open the Easee card -> open 3-dot menu and select Download diagnostics.
You can then drag the downloaded file into a reply in this issue or mail it directly to me at ake@strandberg.eu

**Comment by Lyngaae** [comment]
@astrandb I had to re-configure my integration, and chose my site. It works now and you can close the issue :)

Thank you for your support.

**Comment by Lyngaae** [comment]
@astrandb I had to re-configure my integration, and chose my site. It works now and you can close the issue :)

Thank you for your support.
